### ISSUE TITLE
Help with adding 3 subpackages for dates, strings, and categorical variables

### ISSUE THREAD

**Issue by drizk1** [TidierOrg/Tidier.jl#106]
Hello, 

I have written functions that mirror Forcats, Lubridate, and String. They are TidierCats, TidierDates, and TidierStrings. 

I used pkgTemplate.jl to make packages and upload them to git, but I am experiencing runtest errors and I am not sure how to work around them (even after trying to work through it with GPT4). I am very new git and was hoping a contributor might help me bring these to fruition.  I am happy to transfer ownership/ go thru any other mechanism that is most convenient to bring it to TIdier.jl.

[TidierCats](https://github.com/drizk1/TidierCats)
[TidierDates](https://github.com/drizk1/TidierDates)
[TidierStrings](https://github.com/drizk1/TidierStrings)

**Comment by kdpsingh** [comment]
@drizk1, really nice work in drafting these packages! Going to close this issue since we already transferred the packages over to TidierOrg.

We will work on getting those packages cleaned up.
