### ISSUE TITLE
Adding TidierVest.jl

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/Tidier.jl#121]
I am planning to add TidierVest.jl as a dependency to Tidier.jl so that it gets automatically installed when you install Tidier.jl (similar to how tidyverse works).

However, in R's tidyverse, rvest isn't automatically re-exported into the namespace. I'm thinking we may diverge from that behavior in Tidier.jl and re-export all base packages. If a user is truly using Tidier.jl, then we should make sure that all of the underlying package functions are available to them so they don't have to keep track of this behavior.

If anyone disagrees with this approach, feel free to share thoughts here.

@jdiaz97, let me know if you have any thoughts on this. Thanks!

**Comment by kdpsingh** [comment]
@rdboyes any thoughts on this?

**Comment by rdboyes** [comment]
I think the expectation as a user would be that Tidier makes all Tidier*** packages available, so it makes sense to include TidierVest. People with specific requirements can import package-by-package

**Comment by kdpsingh** [comment]
Perfect. Agree that this makes the most sense. 

I'll plan to add TidierVest while also bumping the dependency versions of all the other packages. This way, updating Tidier will ensure that all the base packages get updated to their latest versions.

**Comment by micke754** [comment]
Just an average R Tidyverse user (for work) and fully agree with your approach of including TidierVest.jl within Tidier.jl. We're used to the practice importing the Tidyverse as a whole when you start a project and then narrowing down the imports later on when finishing things up.

**Comment by kdpsingh** [comment]
Thanks @micke754 for sharing that perspective! Have been busy with work, going to take care of this soon.

**Comment by kdpsingh** [comment]
TidierVest.jl is now included with Tidier.jl, so closing this issue!
