### ISSUE TITLE
No documentation.

### ISSUE THREAD

**Issue by mpeters2** [TidierOrg/Tidier.jl#124]
Add documentation!

**Comment by kdpsingh** [comment]
I 100% agree there's more we can do on the documentation front -- especially on how all the packages fit together -- but have you seen the documentation page for Tidier.jl and for the underlying base packages?

1. Tidier.jl: https://tidierorg.github.io/Tidier.jl/dev/

2. TidierData.jl: https://tidierorg.github.io/TidierData.jl/latest/

And so on...

**Comment by kdpsingh** [comment]
I'm going to close this issue for now. We will continue to think of ways to make the documentation more explanatory/cohesive/centralized. If you have suggestions, feel free to reply to this thread.
