### ISSUE TITLE
Not sure if Tidier.jl is reexporting.. 

### ISSUE THREAD

**Issue by drizk1** [TidierOrg/Tidier.jl#126]
I updated the package and was curious to try just `using Tidier` to access the other package, but I am getting errors when trying to use `@nest` or `str_detect`, but `@filter` for example works, otherwise I have to write `using TIdierData` (for `@nest`) or `using TidierStrings` for `str_detect`

it is also possible there is an issue on my end in which case I will figure it out. Just wanted to make sure it's not universal

**Comment by kdpsingh** [comment]
Go to the package console and type in `status`. What versions of Tidier/TidierData are in your environment?

**Comment by drizk1** [comment]
```
⌃ [f0413319] Tidier v0.7.7
  [79ddc9fe] TidierCats v0.1.1
  [fe2206b3] TidierData v0.14.4
  [20186a3f] TidierDates v0.2.0
  [337ecbd1] TidierPlots v0.5.3
  [248e6834] TidierStrings v0.2.0
  [8f0b679f] TidierText v0.1.1 `https://github.com/TidierOrg/TidierText.jl#main`
  [969b988e] TidierVest v0.4.3
```

**Comment by kdpsingh** [comment]
Try updating Tidier itself. That's a really old version of Tidier.

**Comment by drizk1** [comment]
Sweet. It worked. Strange, when i went to update Tidier this am it went to .7.7 but just now it went 1.2 and everything works. Happy the issue was just on my end.
