### ISSUE TITLE
Standardizing Julia versions across the Tidier ecosystem

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/Tidier.jl#130]
As I'm trying to re-build Tidier.jl, I'm running into issues where the different subpackages within the ecosystem have different requirements for Julia versions. This is causing certain CI tests for Tidier.jl to fail.

Tidier itself requires Julia 1.6, TidierDB requires 1.9, and TidierPlots currently requires Julia 1.10.

In the interest of maintaining compatibility with older versions of Julia, can we relax the Julia version requirement to be either 1.6 for all packages? Or at least to as far back as 1.9?

Makie allows for going back as far as Julia 1.3, but I'm not sure if any of the packages in our ecosystem are relying on newer Julia features such that we can't support older versions.

@drizk1 @rdboyes @jdiaz97 what do you think?

**Comment by drizk1** [comment]
When I was building TidierDB I just picked 1.9 based on gestalt feeling. I just checked on all the packages except (duckdb) and it looks like dropping it 1.6 will cause no issues w the DB packages (which I'm hoping to move to package extensions soon), so it should be ok from my end

**Comment by kdpsingh** [comment]
Actually, package extensions are only available in Julia 1.9. There is a way to make them work pre-1.9 (https://discourse.julialang.org/t/package-extensions-for-julia-1-9/93397) but it requires some work, and may be too much for us to worry about right now.

How about we standardize at Julia 1.9 then?

**Comment by rdboyes** [comment]
Julia 1.9 is fine, but anything before it is borderline unusable (compilation speed increases) - this is improved even more in 1.10 if I recall correctly. Is there a way to set a "suggests" for 1.10?

**Comment by rdboyes** [comment]
Actually ... is there anyone who should reasonably be using 1.9 right now? If we aren't going to support back to 1.6 (Long term stable), shouldn't we just require 1.10?

**Comment by kdpsingh** [comment]
There is at least the possibility of folks who have 1.9 installed at work on a VM for whom Tidier would be unavailable without forcing the issue of an upgrade.

1.9 certainly doesn't have to be the recommended version (latest is generally the best), but it could be a good fallback version as long as the package works.

**Comment by rdboyes** [comment]
That makes sense to me - I can change the version requirements in TidierPlots and add 1.9 as a test version to make sure nothing weird happens

**Comment by rdboyes** [comment]
https://github.com/JuliaRegistries/General/pull/104574 will merge 0.6.6 with a edited test suite that runs correctly under julia 1.9. compat is updated as well

**Comment by kdpsingh** [comment]
Thank you for doing that. I'll review and fix the other packages later today and can hopefully have new docs merged by tonight or tomorrow.

**Comment by kdpsingh** [comment]
For now, we are okay, so I'm going to close this issue. Some of the base packages still allow Julia 1.6, but TIdier.jl itself requires 1.9. We will update the minimum Julia for the base packages (and the related CI) over time. The important thing is that none of the base packages should be *more* stringent than Tidier.jl (e.g., requiring 1.10), which can cause Tidier.jl to fail to build.
