### ISSUE TITLE
Too much recompilation when `using Tidier`

### ISSUE THREAD

**Issue by camilogarciabotero** [TidierOrg/Tidier.jl#135]
Since this is a meta-package I know it reexports all the other packages using `Reexport.jl`. This is cool, but it could take more than 50 % of the loading time in recompilation!

```julia
@time using Tidier

  9.802069 seconds (4.13 M allocations: 270.918 MiB, 9.41% gc time, 14.49% compilation time: 54% of which was recompilation)
```

This concerns all the reexported packages exporting `DataFrames` and similar common packages. I don't know any solution to that, but maybe having `Reexport.jl` more intelligently reexport packages...

**Comment by camilogarciabotero** [comment]
There might be tedious solution: reexport general tools like `DataFrames`, `CSV` and others that are commonly used in the Tidier ecosystem, and then reexport the specific public exports from each Tidier library?

**Comment by kdpsingh** [comment]
I'm open to ideas. In general, Tidier is intended to come batteries included and meant only for interactive use.

Folks with time-sensitive workflows should probably import the specific sub-packages they need individually. Importantly, the base packages all need to also work out of the box, which is why there's lots of re-exporting of portions of DataFrames, etc.

But if there's a way to make the situation better, happy to look.

**Comment by kdpsingh** [comment]
> There might be tedious solution: reexport general tools like `DataFrames`, `CSV` and others that are commonly used in the Tidier ecosystem, and then reexport the specific public exports from each Tidier library?

Hmmm, let's put this in our back pocket once the ecosystem is more mature and we have a larger user base. Tidier itself right now is quite low-maintenance, and I think there's a huge advantage to that bc it lets us innovate faster on the base packages.

**Comment by kdpsingh** [comment]
Let's close this issue for now. Will revisit once the base packages mature more.

**Comment by camilogarciabotero** [comment]
> 10 seconds is acceptable for the "batteries included" version

I agree, maybe when reaching a more stable and mature this could be concern.
