### ISSUE TITLE
Add TidierDB.jl and TidierFiles.jl

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/Tidier.jl#136]
In doing so, I need to ensure dependencies are consistent, see: https://discourse.julialang.org/t/installation-issues-for-tidierdb-with-tidier/112967

**Comment by drizk1** [comment]
Shoutout to that person for the catch. I suspect TidierDB should be able to drop to .5 for chain without an issue.

**Comment by kdpsingh** [comment]
I was stuck on why TidierDB was having issues but think I've figured out why. Even though we had updated TidierData to rely on Chain.jl v0.6, we never released the updated version of TidierData to the registry. Once the new TIdierData is on the registry, the packages should all be compatible.

**Comment by kdpsingh** [comment]
TidierDB and TidierFiles are now available in Tidier v1.4.0.
