### ISSUE TITLE
fix links to docs

### ISSUE THREAD

**Issue by lazarusA** [TidierOrg/Tidier.jl#85]
With the transition to TidierOrg all links associated to Tidier.jl need to be updated.

**Comment by kdpsingh** [comment]
Good catch! Agree we should do a find/replace for pretty much the entire repo.

**Comment by kdpsingh** [comment]
After we clean that up, I may push this to the Julia registry as a patch release just so we can get the repository correctly linked in the registry (instead of relying on auto-forwarding)
