### ISSUE TITLE
Update `Package.toml` to avoid problems with future releases

### ISSUE THREAD

**Issue by pitmonticone** [TidierOrg/Tidier.jl#87]
Hi everyone, 

I'm writing this issue as a reminder to update the repo URL included in the [`Package.toml`](https://github.com/JuliaRegistries/General/blob/master/T/Tidier/Package.toml) file in the Julia general registry in order to avoid problems with future releases of the package. 

If it's ok for you I can immediately open a PR there and close this issue.

**Comment by kdpsingh** [comment]
Just filed a PR to fix this.

**Comment by pitmonticone** [comment]
Great @kdpsingh,

**Comment by kdpsingh** [comment]
Our PR was merged. I just tested it out by pushing out a patch release and everything works.

Two things are still problems but are separate issues:

- I still need to set up deploy keys do that stable docs get updated.
- The registration GitHub action you had set up gave me an error last time I tried to use it. Haven't retried it yet.

**Comment by pitmonticone** [comment]
> Our PR was merged. I just tested it out by pushing out a patch release and everything works.

Great @kdpsingh. 

> I still need to set up deploy keys so that stable docs get updated.

Ok, let me know if that definitely solves the problem by replying in the associated issue.

> The registration GitHub action you had set up gave me an error last time I tried to use it. Haven't retried it yet.

I see. Let me know if it currently works and, if it doesn't, I'll take a look at it.
