### ISSUE TITLE
Add support for multiple columns in `@distinct()`

### ISSUE THREAD

**Issue by christophscheuch** [TidierOrg/Tidier.jl#92]
So `@distinct()` currently only supports one column while the `tidverse` counterpart supports arbitrary columns. Would be great to have support for multiple columns if that is possible. Here is an example:
```
using Tidier

df = DataFrame(a = repeat(1:10, inner = 2), b = repeat('a':'e', inner = 4))

@chain df begin
    @distinct(a, b)
end
```
However, I believe as a workaround, one can also use row filters by group, right? 
```
@chain df begin
    @group_by(a, b)
    @filter(row_number() == 1)
    @ungroup()
end
```

**Comment by kdpsingh** [comment]
Multiple columns should already be supported for `@distinct()`. When I get some downtime I'll double-check this.

Does it generate an error or is the output just not what you expect?

**Comment by christophscheuch** [comment]
It generates the following error message:
```
MethodError: no method matching unique(::DataFrame, ::Symbol, ::Symbol)
```

**Comment by kdpsingh** [comment]
Ooh, thanks for catching this! Will fix.

This is probably because `select()` and `unique()` have slightly different syntax in DataFrames.jl.

**Comment by kdpsingh** [comment]
This should be an easy fix. Will fix this one next.

**Comment by kdpsingh** [comment]
Ok this should be resolved now. `@distinct()` now supports no columns, one column, multiple columns, and even selection helpers.
